version: '3'  # version of compose format 

services:
  observatory-service:
    build: ./observatory  # path is relative to docker-compose.yml localtion
    volumes:
      - ./observatory:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container

#  gohttp-service:
#    build: ./hello_docker_go  # path is relative to docker-compose.yml localtion
#    volumes:
#      - ./hello_docker_go:/usr/src/app # mount point
#    ports:
#      - 5003:80  # host:container
      
#  website:
#    image: php:apache  # pulling image from DockerHub
#    volumes:
#      - ./web:/var/www/html # mount
#    ports:
#      - 5000:80  # host:container
#    depends_on:
#      - observatory-service  # website is not going to work 
#                             # unless observatory-service is running
#      - gohttp-service
                            
#  pyrequestapi-service:
#    build: ./pyrequestapi  # path is relative to docker-compose.yml localtion
#    volumes:
#      - ./pyrequestapi:/usr/src/app # mount point
#    ports:
#      - 5002:8080  # host:container
#      
#    depends_on:
#      - observatory-service  # website is not going to work 
                             # unless observatory-service is running
#      - gohttp-service
                             
  gohttp-restapi:
    build: ./goclientRESTapi  # path is relative to docker-compose.yml localtion
    volumes:
      - ./goclientRESTapi:/usr/src/app # mount point
    ports:
      - 5003:80  # host:container                             
    depends_on:
      - observatory-service  # website is not going to work 
                             # unless observatory-service is running
#      - gohttp-service
 
